<!DOCTYPE html>
<html>

<head>
    <title>Halal Manifest</title>
    <style>
        body {
            font-family: sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <h2>Halal Logistics Manifest</h2>
    <p>Date: {{ $generatedAt->format('Y-m-d H:i') }}</p>
    <p>Generated By: {{ $generatedBy }}</p>
    <table>
        <thead>
            <tr>
                <th>Batch ID</th>
                <th>Product</th>
                <th>Status</th>
                <th>Origin</th>
                <th>Processor</th>
                <th>Current Holder</th>
            </tr>
        </thead>
        <tbody>
            @forelse($batches as $batch)
                <tr>
                    <td>{{ $batch->batch_id }}</td>
                    <td>{{ $batch->product_type }}</td>
                    <td>{{ $batch->status }}</td>
                    <td>{{ $batch->origin_farm }}</td>
                    <td>{{ $batch->processor?->name ?? 'Unknown' }}</td>
                    <td>{{ $batch->currentHolder?->name ?? 'Unassigned' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6">No batches available for this report.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>

</html>
